imports:
    - { resource: config.yml }

framework:
    router:   { resource: '%kernel.root_dir%/config/routing_dev.yml' }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: !doctrine
        firephp:
            type:  firephp
            level: info
        doctrine:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%-doctrine.log'
            channels: doctrine

assetic:
    use_controller: true

swiftmailer:
    disable_delivery:  true
